### ISSUE TITLE
liquidation 时MAXliquidation数据的逻辑问题

### ISSUE THREAD

**Issue by LENDFORME** [Lendfme/liquidator#5]
<img width="377" alt="image" src="https://user-images.githubusercontent.com/56536520/71444748-b1138400-274e-11ea-9242-0d56a606f6dc.png">

1. 页面的自动刷新会把已经选好的内容刷新成默认的；
2. 如图的情况下，切换supply资产，MAX Liquidation数值没有更新；（点击数值后会刷新）

**Comment by DreamGaoYang** [comment]
fixed
