### ISSUE TITLE
交易发出后，按钮用动画方式展示正在执行

### ISSUE THREAD

**Issue by LENDFORME** [Lendfme/liquidator#9]
只有两个按钮：解锁和Liquidate
1. 交易发出后，按钮变成“正在发送交易”的样式，只在当前状态下展示。
2. 刷新页面，关闭页面重新打开后，均恢复默认状态。

<img width="414" alt="image" src="https://user-images.githubusercontent.com/56536520/71455132-ae587380-27ce-11ea-9c08-0def16f5d293.png">

**Comment by DreamGaoYang** [comment]
update

**Comment by LENDFORME** [comment]
还有几个问题：
1. 输入数量是0，或者点击Max是0时;
2. 用户要清算自己的的账户时；
应该disable LIQUIDATE按钮，不允许调起Metamask
